app:
  base-url: "http://localhost:8080"

spring:
  application:
    name: COD-VORTEX

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/cod_vortex_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: mail.codvortex.com
    port: 25
    username: support@codvortex.com
    password: Support123yass

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
